title: ""
logo: "/images/12-webp.webp?raw=true" # Your photo (or logo) here
description: >
  <br><br>
  <div class="link-container">
    <a href="https://www.linkedin.com/in/muntasimulhaque/" target="_blank">ğŸ’¼ LinkedIn</a> <br>
    <a href="https://scholar.google.com/citations?user=qsD8a0MAAAAJ" target="_blank">ğŸ“ Google Scholar</a> <br>
    <a href="https://x.com/muntasimulhaque" target="_blank">ğ• Twitter</a> <br>
    <a href="mailto:muntasim.haque@gmail.com">ğŸ“§ muntasim.haque@gmail.com</a>
  </div>
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
google_analytics: G-W103ZQZ47W # Your Google Analytics tracking ID
